[project]
name = "hunyuan-life"
version = "0.1.7"
description = "Hunyuan Life"
authors = [
    { name = "YuanqiMcp", email = "yuanqi_mcp@tencent.com" },
]
readme = "README.md"
classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
]
keywords = [
    "hunyuan",
    "life",
    "mcp"
]
requires-python = ">=3.11"
dependencies = [
    "mcp[cli]>=1.6.0",
    "httpx==0.28.1",
    "uvicorn==0.34.2"
]

[project.scripts]
hunyuan-life = "hunyuan_life.main:run_mcp"

[build-system]
requires = ["setuptools>=45", "wheel"]
build-backend = "setuptools.build_meta"
