[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "vicon"
version = "0.2.2"
description = "VICON - Viral Conserved Sequence Extraction Toolkit with logging support"
readme = "README.md"
license = "MIT"
requires-python = ">=3.7"

authors = [
    {name = "Ehsan Karimiara", email = "e.karimiara@gmail.com" }
]

dependencies = [
    "numpy>=1.24",
    "pandas",
    "matplotlib",
    "vsearch",
    "pyyaml"
]

[project.urls]
Homepage = "https://github.com/EhsanKA/vicon"

[project.scripts]
vicon-run = "vicon.run_pipeline:main"

[tool.setuptools]
packages = [
    "vicon",
    "vicon.dereplication",
    "vicon.alignment",
    "vicon.processing",
    "vicon.visualization",
    "vicon.io",
    "vicon.utils"
]
include-package-data = true

[tool.setuptools.package-data]
vicon = ["scripts/viralmsa.py"]

[tool.setuptools.data-files]
"bin" = ["vicon/scripts/ViralMSA.py"]