[project]
name = "pixiv-hot-mcp"
version = "0.1.2"
description = "get the hot picture with tag from pixiv"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "beautifulsoup4>=4.13.4",
    "mcp[cli]>=1.9.3",
    "requests>=2.32.4",
]
