[project]
name = "my_code_project"
version = "0.3.52"
description = ""
requires-python = ">=3.11"
readme = "README.md"
dependencies = [
    "setuptools",
    "cython",
    "parso",
    "py7zr",
    "python-dotenv",
]
authors = [
    { name = "Jean-Pierre Morard", email = "focus@thalesgroup.com" },
]

[project.license]
text = "Thales SIX GTS France SAS"

[project.optional-dependencies]
agi-worker = []
dag-worker = [
    "polars",
]
data-worker = [
    "polars",
]
workers = [
    "agi-core[dag-worker]",
    "agi-core[agi-worker]",
]
managers = [
    "agi-core[managers]",
]

[dependency-groups]
dev = [
    "black",
    "pytest",
    "licensecheck",
    "my_code_project",
    "ipython",
]


# do not remove
[tool.uv.sources]
agi-core = {path = "/home/pcm/PycharmProjects/agilab/src/agilab/fwk/core", editable = true}
[tool.uv.sources.my_code_project]
workspace = true

[tool.setuptools]
include-package-data = true

[tool.setuptools.data-files]
my_code = [
    "src/*.ipynb",
    "src/*.json",
    "src/*.toml",
]

[tool.mypy]
mypy_path = [
    "stubs",
]
disallow_untyped_defs = false
ignore_missing_imports = true
