[project]
name = "fastbackfilter"
version = "1.3.2"
description = "JSON generator for data filtration"
requires-python = ">=3.9"
dependencies = [
  "pydantic>=2.7",
  "cachetools>=5.3",
  "platformdirs>=4.2"
]
[build-system]
requires = ["setuptools>=61", "wheel"]
build-backend = "setuptools.build_meta"
[project.scripts]
fastbackfilter = "fastbackfilter.cli:main"
[tool.setuptools]
package-dir = {"" = "."}
[tool.setuptools.packages.find]
where    = ["."]
include  = ["fastbackfilter", "fastbackfilter.*"]
