[project]
name = "stata-mcp"
version = "1.3.7"
description = "Let LLM help you achieve your regression analysis with Stata"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "dotenv>=0.9.9",
    "mcp[cli]>=1.9.0",
    "numpy>=2.2.4",
    "pandas>=2.2.3",
]

[project.scripts]
stata-mcp = "stata_mcp:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
