# [package]
# name = "dout-common"
# version = "0.1.2"
# edition.workspace = true
# authors.workspace = true
# description.workspace = true

# [dependencies]
# hal-common = { version = "0.1.0", path = "../../hal/common" }
# binrw.workspace = true
# num-traits.workspace = true
# libm.workspace = true
# pyo3 = { workspace = true, optional = true}

# [features]
# default = []
# std = ["hal-common/std"]
# pyo3 = ["dep:pyo3", "std", "hal-common/pyo3"]


[package]
name = "dout-common"
version = "0.1.5"
edition = "2021"
authors = ["Julius Walczynski", "Chee Hang Yong"]
description = "RFA Hil Testbench"

[dependencies]
hal-common = { version = "0.1.0", path = "../../hal/common" }
binrw = { version = "0.14.1", default-features = false }
num-traits = { version = "0.2.19", default-features = false }
libm = "0.2.11"
pyo3 = { version = "0.24.0", features = ["extension-module"], optional = true}

[features]
default = []
std = ["hal-common/std"]
pyo3 = ["dep:pyo3", "std", "hal-common/pyo3"]
