[build-system]
requires = ['setuptools>=61.0']
build-backend = 'setuptools.build_meta'

[project]
name = 'evalbench'
version = '1.0.1'
description = "Lightweight, modular library for evaluating LLM outputs with built-in metrics, custom extensions, and agentic workflows."
authors = [
    { name='kotharisanjana', email='sanjanak98@gmail.com' }
]
readme = 'README.md'
license = { text = 'MIT' }
requires-python = '>=3.8'
dependencies = [
    'numpy',
    'nltk',
    'transformers',
    'sentence-transformers',
    'groq',
    'rouge-score',
    'bert-score'
]

[project.optional-dependencies]
dev = [
    'pytest',
]

[tool.setuptools]
package-dir = {'' = 'src'}

[tool.setuptools.packages.find]
where = ['src']
