[tool.poetry]
name = "telegram_libs"
version = "0.1.16"
description = "Common libraries for Telegram bots"
authors = ["Andrey Gritsaenko gricaenko.95a@gmail.com"]
readme = "README.md"
packages = [{include = "telegram_libs", from = "src"}]
repository = "https://github.com/AndreyGritsa/telegram_libs"

[tool.poetry.dependencies]
python = "^3.11"
pytest = "^8.3.5"
python-telegram-bot = "^22.1"
pytest-asyncio = "^1.0.0"
pymongo = "^4.13.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api" 