[project]
name = "sparc-puzzle"
version = "0.1.1"
description = ""
authors = [
    {name = "larskaesberg",email = "larskaesberg@gmail.com"}
]
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "datasets (>=3.6.0,<4.0.0)",
    "openai (>=1.86.0,<2.0.0)"
]

[project.scripts]
sparc = "sparc.sparc:main"

[tool.poetry]
name = "sparc-puzzle"
description = ""
authors = ["larskaesberg <larskaesberg@gmail.com>"]
readme = "README.md"
packages = [{include = "sparc"}]

[tool.poetry.dependencies]
python = "^3.10"

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
