[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "big-thing-py"
version = "0.4.3.1-13"
description = "JOI Smart Device SDK"
authors = [
    {name = "MySmaXLab", email = "mysmaxlab@gmail.com"}
]
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "termcolor",
    "getmac",
    "gmqtt",
    "requests",
    "websockets",
    "typing-extensions>=4.0",
    "bless",
    "dbus-next",
    "uvloop>=0.19.0; sys_platform != 'win32'",
    "zeroconf",
    "aenum",
    "jsonschema",
    "python-gettext",
    "tinykv",
    "toml"
]

[project.optional-dependencies]
dev = [
    "tox",
    "pytest",
    "pytest-timeout",
    "pytest-asyncio"
]

[tool.hatch.build.targets.wheel]
packages = ["big_thing_py"]

[tool.hatch.build.targets.sdist]
include = [
    "/big_thing_py",
    "/README.md",
    "/LICENSE",
]
