name: multirtc
channels:
  - conda-forge
  - nodefaults
dependencies:
  # For running
  - python
  - pip
  - gdal>=3.0
  - numpy>=1.20
  - isce3
  - boto3
  - requests
  - lxml
  - shapely
  - pyproj
  - s1reader>=0.2.5
  - sarpy
  - burst2safe
  - tqdm
  - hyp3lib
  # For packaging, and testing
  - setuptools
  - setuptools_scm
  - wheel
  - pytest
  - pytest-console-scripts
  - pytest-cov
  - ruff
