[project]
name = "gai-asm"
version = "0.1.0"
readme = "README.md"
license = {file = "LICENSE"}
authors = [
    { name = "kakkoii1337", email = "kakkoii1337@gmail.com" }
]
requires-python = ">=3.10"
dependencies = [
    "gai-lib",
    "transitions==0.9.2",
]
[project.optional-dependencies]
    dev = ["gai-lib[dev]"]

[dependency-groups]
    dev = ["gai-lib[dev]"]

[tool.uv.sources]
    "gai-lib" = { path="../lib", editable = true }

[build-system]
    requires = [ "hatchling",]
    build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
    packages = [ "src/gai"]
