[project]
name = "cgback"
version = "1.0.2"
description = "Deep learning tool for backmapping coarse-grained to all-atom"
readme = "README.md"
authors = [
    { name = "Diego Ugarte", email = "diego.ugarte@outlook.com" }
]
requires-python = ">=3.10.0"
dependencies = [
    "numpy>=2.1.0",
    "rich>=13.9.4",
    "scipy>=1.15.0",
    "torch>=2.5.0",
]
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]
license = { file = "LICENSE" }

[project.scripts]
cgback = "cgback.backmapper_app:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project.optional-dependencies]
openmm = ["openmm>=8.2.0"]
openmm-cuda12 = ["openmm[cuda12]>=8.2.0"]

[tool.uv]
conflicts = [
    [
        { extra = "openmm" },
        { extra = "openmm-cuda12" },
    ],
]

[project.urls]
Repository = "https://github.com/bondrewd/cgback"

[dependency-groups]
dev = [
    "pytest>=8.3.5",
]
