[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "simcombustion"
version = "0.1.0"
authors = [
  { name="Nicolás Herrera Fernández", email="ni.herrefer@gmail.com" },
]
description = "Una librería para análisis de combustión con Cantera."
readme = "README.md"
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Intended Audience :: Science/Research",
    "Topic :: Scientific/Engineering :: Chemistry",
]
dependencies = [
    "numpy",
    "cantera>=3.1.0",
]

[tool.setuptools.packages.find]
where = ["."]

[tool.setuptools.package-data]
# Incluye los datos del paquete 'simcombustion'
"simcombustion" = ["data/*.yaml"]  # <-- CAMBIO AQUÍ