[project]
name = "veri-agents-knowledgebase"
version = "0.1.3.4"
description = "Add your description here"
authors = [
  {name = "Markus Toman", email = "mtoman@veritone.com"},
  {name = "Teo Boley", email = "tboley@veritone.com"},
]
requires-python = ">=3.12"
dependencies = [
  "veri-agents-common==0.1.1",
  "cachetools>=5.5.2"
]

[project.optional-dependencies]
graphs = [
  "veri-agents-common[langgraph]==0.1.1",
]
qdrant = [
  "veri-agents-common[qdrant,docling,fastembed]==0.1.1",
]
all = ["veri-agents-knowledgebase[graphs,qdrant]==0.1.3"]
# as optional dep so it can be referenced in workspace pyproject.toml
dev = ["veri-agents-knowledgebase[all]==0.1.3"]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
