[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"


[project]
name = "prematricula"
version = "0.0.4"
authors = [
  { name="Mauricio Andrés Zamora Hernández", email="mauricio.zamorahernandez.ucr@gmail.com" },
]
description = "Software de soporte de revisión de pre-matrículas para la escuela de ingeniería industrial"
readme = "README.md"
requires-python = ">=3.10"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Development Status :: 3 - Alpha",
    "Environment :: Console",
    "Intended Audience :: Education",
    "License :: OSI Approved :: MIT License",
    "Natural Language :: Spanish"
]
dependencies = [
     "pyperclip","requests","termcolor","XlsxWriter",
]

[project.urls]
"Homepage" = "https://github.com/mauricio-zamora/prematricula"
"Bug Tracker" = "https://github.com/mauricio-zamora/prematricula/issues"

[project.scripts]
prematriculas = "prematricula.main:main"