[package]
name = "zkbp"
version = "0.1.5"
edition = "2021"
description = "ZK interface for python ledger"
readme = "README.md"  # ðŸ‘ˆ THIS is required
license = "Apache-2.0"
repository = "https://github.com/jpmorganchase/padl"
keywords = ["zk", "crypto", "bn254"]

[tool.maturin]
module-name = "zkbp"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "zkbp"
crate-type = ["cdylib"]

[patch.crates-io]
curv-kzen = {path="./curv"}
bulletproof-kzen = {path="./bulletproofs"}

[dependencies]
curv-kzen = {default-features = false, features= ["num-bigint"],path="./curv" }
sha2 = "0.9"
bulletproof-kzen = {version="1.2.1", default-features = false}
pyo3 = { version = "0.17.3", features = ["extension-module","abi3-py39"] }
serde = "1.0"
serde_json ="1.0"
serde_derive = "1.0"
digest = "0.9"
json_value_merge = "2.0.0"
rand = "0.7"
rand_legacy = { package = "rand", version = "0.6" }
rand_core = "0.4.0"
