[project]
name = 'ankipan'
description = 'A language learning utility with Anki integration'
version = '0.1'

authors = [
    {name = 'Daniel Otto de Mentock', email = 'daniel.mentock@gmail.com'}
]

classifiers = [
    'Intended Audience :: Education',
    'Topic :: Education',
    'License :: OSI Approved :: GNU Affero General Public License v3 or later (AGPLv3+)',
    'Operating System :: OS Independent',
    'Programming Language :: Python',
    'Programming Language :: Python :: 3',
    'Programming Language :: Python :: 3.10',
    'Programming Language :: Python :: 3.11',
    'Programming Language :: Python :: 3.12',
    'Programming Language :: Python :: 3.13',
    'Programming Language :: Python :: 3 :: Only',
    'Typing :: Typed'
]

requires-python = '>=3.10'
dependencies = [
    'beautifulsoup4',
    'ipython',
    'ipywidgets',
    'langdetect',
    'lxml',
    'numpy',
    'pysubs2',
    'requests',
    'python-dotenv'
]

readme = 'README.md'

[project.urls]
repository = 'https://gitlab.com/ankipan/ankipan'


[build-system]
requires = ['setuptools >= 59.0']
build-backend = 'setuptools.build_meta'
