[project]
name = "heroui-provider"
version = "0.1.4"
description = "Hero UI - Modern UI components for Reflex Web Framework"
readme = "README.md"
authors = [
    { name = "Adarsh Gourab Mahalik", email = "gourabmahalikadarsh@gmail.com" },
]
requires-python = ">=3.10"
dependencies = ["reflex>=0.7.14"]
classifiers = [
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.optional-dependencies]
dev = [
    "uv>=0.7.12",
    "pytest>=8.4.0",
    "black>=25.1.0",
    "mypy>=1.16.0",
]
all = ["reflex>=0.7.14"]

[project.entry-points."reflex.components"]
heroui = "heroui"

[project.urls]
"Homepage" = "https://github.com/adarshgm/heroui"
"Bug Tracker" = "https://github.com/adarshgm/heroui/issues"

[build-system]
requires = ["hatchling>=1.27.0", "uv>=0.7.12"]
build-backend = "hatchling.build"

[tool.hatch.build]
packages = ["src", "heroui"]

[tool.hatch.build.targets.wheel]
packages = ["src", "heroui"]

[tool.hatch.build.targets.sdist]
include = ["src", "heroui", "README.md", "LICENSE"]
