[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "ODConvert"
version = "0.0.3"
description = "A simplistic CLI for converting between object detection dataset formats"
authors = [{ name = "Jack Devey", email = "jack.devey@bcu.ac.uk" }]
dynamic = ["dependencies"]

[project.scripts]
odc = "ODConvert.__main__:main"

[tool.setuptools.dynamic]
dependencies = {file = ["requirements.txt"]}
