[build-system]
requires = ["setuptools","gdown","ollama"]
build-backend = "setuptools.build_meta"

[project]
name = "ezcmt"
version = "0.1.6"
description = "A simple and free CLI tool for Git"
readme = "README.md"
authors = [{name = "mmemoo"}]
requires-python = ">=3.10.0"

[project.scripts]
ezcmt = "cli_tool.main:main"

[tool.setuptools]
include-package-data = true

[tool.setuptools.package-data]
"cli_tool" = ["*"]