[build-system]
requires = ["setuptools >= 77.0.3"]
build-backend = "setuptools.build_meta"

[project]
name = "data_retriever"
version = "1.12"
authors = [
  { name="Nelly Barret", email="nelly.barret@polimi.it" },
]
description = "The package to retrieve data from ETL-built databases. Part of the BETTER project."
readme = "README.md"
requires-python = ">=3.9"
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]
license = "MIT"
license-files = ["LICEN[CS]E*"]

[project.urls]
Homepage = "https://www.better-health-project.eu/"
Issues = "https://git.rwth-aachen.de/padme-development/external/better/data-cataloging/etl/-/issues"