[project]
name = "tasty-agent"
version = "0.2.2"
description = "A Model Context Protocol server for interacting with TastyTrade brokerage accounts"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "keyring",
    "mcp[cli]",
    "tastytrade",
    "exchange-calendars",
    "tabulate",
]
authors = [{ name = "Ferdous", email = "ferdous@hey.com" }]
keywords = ["tastytrade", "trading", "mcp", "model context protocol", "broker", "robinhood", "wallstreetbets"]
classifiers = [
    "Intended Audience :: Financial and Insurance Industry",
    "Intended Audience :: End Users/Desktop",
    "Topic :: Office/Business :: Financial",
    "Programming Language :: Python :: 3.12",
    "License :: OSI Approved :: MIT License",
]

[project.scripts]
tasty-agent = "src.tasty_agent.cli:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src"]
