[build-system]
requires = ["setuptools>=78.1.0"]
build-backend = "setuptools.build_meta"
[project]
name = "moviessdk_Pricile"
version = "0.0.3"
authors = [
 { name="[GaÃ«lle Pricile GANGBE]" },
]
description = "Software Development Kit (SDK) for MovieLens API"
readme = "README.md"
requires-python = ">=3.11"
classifiers = [
 "Development Status :: 3 - Alpha",
 "Programming Language :: Python :: 3",
 "License :: OSI Approved :: MIT License",
 "Operating System :: OS Independent",
]
dependencies = [
 'httpx>=0.28.1',
 'pydantic>=2.11.2',
 'backoff>=2.2.1',
 'python-dotenv',
]