[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "radis-app"
version = "0.1.4"
description = "A simple CLI app that prints personal info"
authors = [
  { name = "Radiela Yorgova", email = "you@example.com" }
]
readme = "README.md"
license = { file = "LICENSE"}
eula = {file = "EULA"}
requires-python = ">=3.8"
dependencies = []

[project.scripts]
radis-app = "myApp.main:main"

[tool.hatch.build.targets.wheel]
packages = ["myApp"]

