[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "moanapi"
version = "0.3.0"
authors = [
  { name="mineogo", email="venkatesh10year@gmail.com" },
]
description = "A dynamic, auto-updating Python wrapper for the Moan API suite."
readme = "README.md"
license = { file = "LICENSE" }
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
    "Topic :: Software Development :: Libraries :: Python Modules",
    "Intended Audience :: Developers",
]
dependencies = [
    "requests>=2.25.0",
]

[project.urls]
Homepage = "https://moanapi.ddns.net"
"Bug Tracker" = "https://moanapi.duckdns.net/module/report-bug"
