[project]
name = "ignorely"
version = "1.2.0"
description = ""
authors = [
    {name = "Sisung Kim",email = "sisung.kim1@gmail.com"}
]
readme = "README.md"
requires-python = ">=3.10,<4.0"
dependencies = [
    "cleo (>=2.1.0,<3.0.0)",
    "pathspec (>=0.12.1,<0.13.0)"
]

[project.scripts]
ignorely = "ignorely.main:main"

[tool.poetry.group.dev.dependencies]
pytest = "^8.3.5"

