[build-system]
requires = ["setuptools>=45", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "alumathgroup3"
version = "1.0.0"
description = "A simple Python library for matrix multiplication"
readme = "README.md"
authors = [{name = "Erneste Ntezirizaza", email = "erneste.ntezirizaza@gmail.com"}]
license = {text = "MIT"}
classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3",
]
requires-python = ">=3.6"
