[project]
name = "flashboot-core"
version = "0.1.14"
description = "A springboot likely framework for python."
requires-python = ">=3.10"
dependencies = [
    "commons-lang>=0.2.13",
    "loguru>=0.7.3",
    "peewee>=3.18.1",
    "playhouse>=0.1.0",
    "pool>=0.1.2.dev0",
    "pydantic>=2.11.4",
    "pydantic-yaml>=1.4.0",
    "pymysql>=1.1.1",
    "pyyaml>=6.0.2",
]

[tool.setuptools.packages.find]
where = ["."]
include = ["flashboot_core"]
exclude = ["test", "resources"]
