[project]
name = "agentbee"
version = "0.0.2"
description = "An AI-powered code assistant to analyze, assist with, and automate code modifications."
readme = "README.md"
requires-python = ">=3.8"
dependencies = [
    "typer[all]",
    "openai",
    "python-dotenv", # Good practice for managing local dev keys
]

[project.scripts]
agentbee = "agentbee.main:app"