[tool.poetry]
name = "chromatopy"
version = "1.8.0"
description = "Peak integration software."
authors = ["Dr. Gerard Otiniano <gerardotiniano@gmail.com>", "Dr. Elizabeth Thomas"]
readme = "README.md"
packages = [{include = "chromatopy", from = "src"}]

[tool.poetry.dependencies]
python = "^3.10"
numpy = "^1.1.0"
pandas = "^2.0.0"
scikit-learn = "^1.0.0"
scipy = "^1.0.0"
setuptools = "69.5.1"
matplotlib = "^3.6.0"
rainbow-api = "1.0.9"
pybaselines = "1.1.0"
tqdm = "^2.0.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
