[build-system]
requires = [ "flit_core>=3.2,<4",]
build-backend = "flit_core.buildapi"

[project]
name = "mmb_layer0"
version = "1.0.1"
description = "MMB blockchain network"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [ "rsa >=4.9.1,<5.0.0", "ecdsa >=0.19.1,<0.20.0", "jsonlight >=0.0.7,<0.0.8", "rich >=14.0.0,<15.0.0", "streamlit >=1.45.1,<2.0.0",]
[[project.authors]]
name = "Lee Min Waan"
email = "100744636+plsgivemeachane@users.noreply.github.com"

[project.license]
text = "MIT"

[tool.flit.sdist]
include = [ "src/",]
