[build-system]
requires = ["setuptools>=42"]
build-backend = "setuptools.build_meta"

[project]
name = "zx_db_manager"
version = "0.1.1"
authors = [
    { name = "MENG", email = "meng@zxtech.info" },
]
description = "A MySQL cloud library"
readme = "README.md"
requires-python = ">=3.12.2"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]




