[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"
[project]
name="py-cv-parser"
version="1.1.1"
authors=[{name="hunny",email="jetchill521@gmail.com"}]
description = "a resume analyze tool"
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: Apache Software License",
    "Operating System :: OS Independent"
]
readme = "README.md"
dependencies = [
    "langdetect~=1.0.9",
"pdfminer.six>=20250506",
"phonenumbers~=9.0.6",
"spacy~=3.8.7",
    "country-converter"
]
[project.urls]
Homepage = "https://github.com/Hunnyisme/cvparser"
