[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "hzzzwl-agriculture-mcp-x"
version = "0.2.5"
authors = [
  {name = "hzzzwl", email = "1085501772@qq.com"},
]
description = "Tools for providing agricultural information"
readme = "README.md"
requires-python = ">=3.12"
classifiers = [
  "Programming Language :: Python :: 3"
]
license = "GPL-3.0"
dependencies = [
    "httpx>=0.28.1",
    "mcp[cli]>=1.9.0",
]

[project.scripts]
hzzzwl-agriculture-mcp-x = "hzzzwl_agriculture_mcp_x.server:main" # 指定默认执行的方法