[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "punigowda"
version = "0.1"
authors = [
  { name = "puneeth", email = "puneethmgowda047@email.com" },
]
description = "A simple example package"
readme = "README.md"
requires-python = ">=3.6"
classifiers = [
  "Programming Language :: Python :: 3",
  "License :: OSI Approved :: MIT License",
  "Operating System :: OS Independent",
]
dependencies = []

[project.urls]
"Homepage" = "https://github.com/yourusername/punigowda"
"Bug Tracker" = "https://github.com/yourusername/punigowda/issues"