[project]
name = "ephor-cli"
version = "0.7.5"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "amandal-cn", email = "mandal.ashish@codenation.co.in" }
]
requires-python = ">=3.13"
dependencies = [
    "boto3==1.38.8",
    "click==8.1.8",
    "colorama==0.4.6",
    "google-adk==0.3.0",
    "langchain>=0.3.25",
    "langchain-anthropic>=0.3.13",
    "langgraph>=0.4.5",
    "mcp>=1.9.3",
    "python-dotenv==1.1.0",
    "google-a2a",
    "langchain-google-genai>=2.1.4",
    "langchain-aws>=0.2.23",
    "langchain-openai>=0.3.18",
]

[project.scripts]
ephor-cli = "ephor_cli:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.uv.sources]
google-a2a = { git = "https://github.com/djsamseng/A2A", subdirectory = "samples/python", branch = "prefixPythonPackage" }
