[project]
name = "t3py"
version = "0.3.1"
description = "CLI util for the T3 API ecosystem"
authors = [{ name = "Matt Frisbie", email = "matt@classvsoftware.com" }]
readme = "README.md"
license = { text = "GPL-3.0-only" }
requires-python = ">=3.8"
dependencies = [
    "rich>=14.0.0",
    "t3api >=0.4.0",
    "t3api-utils>=0.2.0",
    "typer>=0.16.0",
]

keywords = ["t3", "metrc", "utils", "helpers", "track and trace"]
classifiers = [
    "Development Status :: 3 - Alpha",
    "License :: OSI Approved :: GNU General Public License v3 (GPLv3)",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.8",
    "Operating System :: OS Independent",
]

[dependency-groups]
dev = [
    "mypy>=1.14.1",
    "pytest>=8.3.5",
]

[project.scripts]
t3py = "t3py.__main__:app"

[project.urls]
Homepage = "https://github.com/classvsoftware/t3py"

[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[tool.mypy]
files = ["t3py", "tests"]
warn_unused_configs = true
warn_redundant_casts = true
warn_unused_ignores = true
strict_equality = true
extra_checks = true
check_untyped_defs = true
disallow_subclassing_any = true
disallow_untyped_decorators = true
disallow_any_generics = true

[[tool.mypy.overrides]]
module = ["t3py.*"]
warn_unused_ignores = true
strict_equality = true
extra_checks = true
check_untyped_defs = true
disallow_subclassing_any = true
disallow_untyped_decorators = true
disallow_any_generics = true
disallow_untyped_calls = true
disallow_incomplete_defs = true
disallow_untyped_defs = true
no_implicit_reexport = true
warn_return_any = true
